const PRIMARY_COLOR = "#EDF2F8";
const SECONDARY_COLOR = "#313BAC";
const BACK_COLOR = "#030303";
const LIGTHGRAY_COLOR = "#E4E4E4";
const GRAY_COLOR = "#6B7688";
const BROWN_COLOR = "#46364A";
const WHITE_COLOR = "#FFFFFF";

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  BACK_COLOR,
  LIGTHGRAY_COLOR,
  GRAY_COLOR,
  BROWN_COLOR,
  WHITE_COLOR,
};
